from gym_subgoal_automata.envs.disappearing_waterworld.disappearing_waterworld_env import DisappearingWaterWorldEnv
from gym_subgoal_automata.envs.disappearing_waterworld.disappearing_waterworld_env import DisappearingWaterWorldRedEnv
from gym_subgoal_automata.envs.disappearing_waterworld.disappearing_waterworld_env import DisappearingWaterWorldRedGreenEnv
from gym_subgoal_automata.envs.disappearing_waterworld.disappearing_waterworld_env import DisappearingWaterWorldRedGreenBlueEnv
from gym_subgoal_automata.envs.disappearing_waterworld.disappearing_waterworld_env import DisappearingWaterWorldRedGreenBlueCyanEnv
